### PR TITLE
Web SDK v109146 changes:

### PR DESCRIPTION
**Pull request by jasonpang**
- Add fetch handler to repeat network requests due to Firefox v44 not adding Origin header for service-worker-handled CORS requests
- Previous OneSignal caches now deleted on service worker activation

[Review on Reviewable](https://reviewable.io/reviews/one-signal/onesignal-website-sdk/23)

### CODE REVIEW

**Comment by gdeglin** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/serviceWorker.js, line 45 \[r2\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23#-KBvVDGObpErvl7DaAJk:-KBvVDGObpErvl7DaAJl:-1808369759) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6fde655bc83936d3b5ccb0df9b4a25fb66a7c638/src/serviceWorker.js#L45)):*
Is it possible that Browser.version will be something like 44.0.2?

---

*[src/serviceWorker.js, line 403 \[r2\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23#-KBvUv5GNBKP9KQc-O_b:-KBvUv5GNBKP9KQc-O_c:-1722579174) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6fde655bc83936d3b5ccb0df9b4a25fb66a7c638/src/serviceWorker.js#L403)):*
since we're not using the cache, we don't need to clear the cache either, right?

---

*[src/serviceWorker.js, line 422 \[r2\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23#-KBvUfv4BHLrBsY9lzeJ:-KBvUfv4BHLrBsY9lzeK:-677588728) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6fde655bc83936d3b5ccb0df9b4a25fb66a7c638/src/serviceWorker.js#L422)):*
self.refresh_requests isn't needed here since this event handler shouldn't get attached in this case

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23)*

**Comment by jasonpang** [comment]
*[src/serviceWorker.js, line 45 \[r2\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23#-KBvVDGObpErvl7DaAJk:-KBy-eJ5Lfi_pnmHxJjf:45062178) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6fde655bc83936d3b5ccb0df9b4a25fb66a7c638/src/serviceWorker.js#L45)):*
Thanks for catching this, the original code would not have worked at all
. It seems the version returned by the Bowser library is always like "44.0" or "45.0" or "47.0" (tested on release, beta, and Nightly).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23)*

**Comment by jasonpang** [comment]
*[src/serviceWorker.js, line 403 \[r2\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23#-KBvUv5GNBKP9KQc-O_b:-KBy06izW3oubfADpm2u:-433832621) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6fde655bc83936d3b5ccb0df9b4a25fb66a7c638/src/serviceWorker.js#L403)):*
There will still be many previous cache versions left on people's browsers that we haven't cleared before. Now that we're no longer using caches, we just need to clean all of them up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23)*

**Comment by jasonpang** [comment]
*[src/serviceWorker.js, line 422 \[r2\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23#-KBvUfv4BHLrBsY9lzeJ:-KBy0TYLEWi_s76OCWLw:883918160) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6fde655bc83936d3b5ccb0df9b4a25fb66a7c638/src/serviceWorker.js#L422)):*
Simplified (return isn't needed anymore as `respondWith()` returns void).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/23)*

**Pull request merged**
