### PR TITLE
Web SDK changes:

### PR DESCRIPTION
**Pull request by jasonpang**
- Added option to change service worker persistNotification
- Added webhooks to POST back to user-chosen URLs when notification
  displayed or clicked

[Review on Reviewable](https://reviewable.io/reviews/one-signal/onesignal-website-sdk/6)

### CODE REVIEW

**Comment by jkasten2** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sdk.js, line 491 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6#-K87esx6K_CZRIO8MdCN:-K87esx6K_CZRIO8MdCO:1868540194) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/47f0eeff70684164fce7da7dbbcc21856470e68e/src/sdk.js#L491)):*
Something like this would look a little cleaner.

````
let persistNotification = OneSignal._initOptions.persistNotification === true ? true : false;
Database.put('Options', {key: 'persistNotification', value: persistNotification });
```

---

*[src/serviceWorker.js, line 120 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6#-K87fo2yvkoaRi_Irwyi:-K87fo2yvkoaRi_Irwyj:483270253) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/47f0eeff70684164fce7da7dbbcc21856470e68e/src/serviceWorker.js#L120)):*
does 'var promise` here end up as the same instance in the '.then' below? Maybe it should be outside of Promise.all.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6)*
<!-- Sent from Reviewable.io -->

**Comment by jasonpang** [comment]
*[src/sdk.js, line 491 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6#-K87esx6K_CZRIO8MdCN:-K8LghhMvULL2_0_RkBP:49630068) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/47f0eeff70684164fce7da7dbbcc21856470e68e/src/sdk.js#L491)):*
`persistNotification` also defaults to true if omitted, so I wanted to avoid writing:

`var persistNotification = (OneSignal._initOptions.persistNotification === undefined || OneSignal._initOptions.persistNotification)`

Felt it was more direct to just say if false false, otherwise true.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6)*

**Comment by jasonpang** [comment]
*[src/serviceWorker.js, line 120 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6#-K87fo2yvkoaRi_Irwyi:-K8LxhF6Zb_zeo0w9yfi:-499146009) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/47f0eeff70684164fce7da7dbbcc21856470e68e/src/serviceWorker.js#L120)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6)*

**Comment by jasonpang** [comment]
Reviewed 1 of 5 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/6)*

**Pull request merged**
