### PR TITLE
Web SDK changes:

### PR DESCRIPTION
**Pull request by jasonpang**
- Change ES6 function Object.assign() to use custom assign() function
- Change ES6 String.prototype.includes() to use standardized indexOf()
- Fix postMessage() event listener not ignoring messages that don't concern us

[Review on Reviewable](https://reviewable.io/reviews/one-signal/onesignal-website-sdk/5)

### CODE REVIEW

**Comment by jasonpang** [comment]
*[src/sdk.js, line 1160 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xQQR7VnLkQ1qkX8fF:-K7xQQR7VnLkQ1qkX8fG:-2057235474) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/sdk.js#L1160)):*
Fix popup not closing after clicking "Block" in popup.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by jasonpang** [comment]
*[src/sdk.js, line 1213 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xQdz63dXrNEFF4PIt:-K7xQdz63dXrNEFF4PIu:892698548) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/sdk.js#L1213)):*
This block fixes us receiving postMessage() messages we don't care about that we would try to process, but error out because OneSignal._initOptions.subdomainName was undefined and OneSignal._initOptions was *null* and *not* undefined.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by jasonpang** [comment]
Reviewed 3 of 11 files at r1.
Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by gdeglin** [comment]
Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sdk.js, line 1160 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xQQR7VnLkQ1qkX8fF:-K7xQXIZ718PwedReZ5O:678200917) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/sdk.js#L1160)):*
yay!

---

*[src/sdk.js, line 1213 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xQdz63dXrNEFF4PIt:-K7xR3RZxKhR_dQ6TbTd:-16799150) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/sdk.js#L1213)):*

the check for OneSignal._initOptions.subdomainName means that this if will be true and this function will return on an https website. This might be intentional but just double checking...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by jwilm** [comment]
One high level question. Is there a reason we manually write out for loops each time? `Array.forEach`, although slower, is much less error prone. If performance is really an issue (I can't imagine any of these loops are particularly large), maybe we should write an `each` abstraction that is more performant than `Array.forEach`.

---

Reviewed 5 of 11 files at r1.
Review status: 8 of 11 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/api.js, line 47 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xXAF34xPrSsV8bKIJ:-K7xXAF34xPrSsV8bKIK:1803413748) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/api.js#L47)):*
Prefer `indexOf('...') !== -1`.

---

*[src/bell/ActiveAnimatedElement.js, line 52 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xXMCWFfv1CTXOjYuj:-K7xXMCWFfv1CTXOjYuk:-1173117818) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/bell/ActiveAnimatedElement.js#L52)):*
Might be nice to have a helper `stringContains(s, 'substring')` that returns a bool instead of repeating this logic everywhere. `stringContains` has the added benefit of reading more naturally.

---

*[src/serviceWorker.js, line 179 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xXtec-G4CMOPqwei_:-K7xXtec-G4CMOPqweia:-612067486) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/serviceWorker.js#L179)):*
Would read much better as `!stringContains(launchURLObject.search, '_osp=do_not_open')`.

---

*[src/utils.js, line 317 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xY5EtQDKzBq9KnwHa:-K7xY5EtQDKzBq9KnwHb:-1112878522) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/utils.js#L317)):*
prefer `val !== void 0` instead of `val !== undefined`. This is an issue pre ES5 where undefined could be assigned to.

---

*[src/utils.js, line 323 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xYUX_y2Fa1dXGsrRL:-K7xYUX_y2Fa1dXGsrRM:410085122) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/utils.js#L323)):*
A doc string would be nice.

---

*[src/utils.js, line 328 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xYY3mYcqt8cGDnLoG:-K7xYY3mYcqt8cGDnLoH:1707867049) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/utils.js#L328)):*
Why start at 1? Also, prefer `s !== arguments.length` for your loop invariant.

---

*[src/utils.js, line 339 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xZ-nW2Rt9GLb_mpe7:-K7xZ-nW2Rt9GLb_mpe8:-155458500) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/utils.js#L339)):*
Ditto about loop invariant.

---

*[src/utils.js, line 340 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xYsid1DV-FjJBOe_5:-K7xYsid1DV-FjJBOe_6:1171323359) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/utils.js#L340)):*
What is the intent here? (comment the code :smile:)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-:-K7xZ3mDbL8vOEkuwDdh:-729294993)*

**Comment by jasonpang** [comment]
Hey Joe,

Are you referring to the loops in the Object.assign() function? They were lifted from a Object.assign() polyfill from GitHub. Or the code in general?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-:-K7yFI-EjhjGhxWLmTOx:1728323385)*

**Comment by jasonpang** [comment]
*[src/utils.js, line 317 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xY5EtQDKzBq9KnwHa:-K7yJQXK8akIF7nUNEP-:1087858530) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/utils.js#L317)):*
UglifyJS seems to convert these all for us.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by jasonpang** [comment]
*[src/serviceWorker.js, line 179 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xXtec-G4CMOPqwei_:-K7yJawr10H5w41k_36Y:-499146009) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/serviceWorker.js#L179)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by jasonpang** [comment]
*[src/sdk.js, line 1213 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xQdz63dXrNEFF4PIt:-K7yJbxjynQxJ-AxuM4x:1434004978) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/sdk.js#L1213)):*
You're totally right -- thanks for pointing this out! Got that fixed in the next version.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by jasonpang** [comment]
*[src/bell/ActiveAnimatedElement.js, line 52 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xXMCWFfv1CTXOjYuj:-K7yJhRbocvMmd-4dbZw:-942737414) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/bell/ActiveAnimatedElement.js#L52)):*
Done. (but used contains instead of stringContains because I thought that had a nice ring to it :ring: )

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Comment by jasonpang** [comment]
*[src/api.js, line 47 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5#-K7xXAF34xPrSsV8bKIJ:-K7yJo6bUJRrQ-GP9YYd:-499146009) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/6a3d79bb7fa30306f796cc51af24f73a7d5ec7c8/src/api.js#L47)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/5)*

**Pull request merged**
