### PR TITLE
Web SDK changes:

### PR DESCRIPTION
**Pull request by jasonpang**
- Service worker now takes over existing clients once installed, no need
  to close all tabs before new service worker can take effect
- Fix bell taking up too much width in the page (now it takes up the
  bell's size exactly)
- Make bell dialog width static to 200px (used to size according to
  text, not good)
- Lower bell inactive opacity by 10% (was 60%, now 50%)
- Calls to OneSignal API now log exception properly
    - 401 Unauthorized errors are logged and shown a special message
- Using an invalid subdomainName with '.' throws an error and special
  message
- If the Roost service worker is detected to be active, OneSignal's
  service worker is installed over it
- Remove unused code block
- Begin OneSignal.getNotificationPermission() official API, commented
  currently
- Partially try to fix addListenerForOpenedNotification postMessage()
  callback, untested still

[Review on Reviewable](https://reviewable.io/reviews/one-signal/onesignal-website-sdk/3)

### CODE REVIEW

**Comment by gdeglin** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sdk.js, line 872 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rpHMw1k-y_a6vu8bV:-K7rpHMw1k-y_a6vu8bW:-1286797527) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/sdk.js#L872)):*
Can we overwrite other service workers in general instead of singling out Roost?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jasonpang** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sdk.js, line 872 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rpHMw1k-y_a6vu8bV:-K7rpeDlNpJIxec5AIeS:926693465) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/sdk.js#L872)):*
Good point, done!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jwilm** [comment]
Reviewed 6 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/api.js, line 22 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rpf6IjrHBOX-nQ47N:-K7rpf6IjrHBOX-nQ47O:335532964) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/api.js#L22)):*
Maybe this should be `json` instead of `response` since it's different from the last block's argument.

---

*[src/sdk.js, line 449 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rqVZmDyso-cVKBJ4l:-K7rqVZnwtZx8ME6MY9K:1268796017) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/sdk.js#L449)):*
Is this supposed to all be in double quotes?

---

*[src/serviceWorker.js, line 133 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rr1agpdPUyOrfN0UZ:-K7rr1agpdPUyOrfN0U_:807303526) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/serviceWorker.js#L133)):*
No reason to keep commented out debug logs.

---

*[src/serviceWorker.js, line 209 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rrVwlkASjtgpdxnBL:-K7rrVwm5MJlKno6Uzhn:419883860) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/serviceWorker.js#L209)):*
Could just be `.then(() => self.skipWaiting())`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jasonpang** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/sdk.js, line 449 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rqVZmDyso-cVKBJ4l:-K7rs5n9arjbcjvrKx8x:1637797979) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/sdk.js#L449)):*
Oooo good catch.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jasonpang** [comment]
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/api.js, line 22 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rpf6IjrHBOX-nQ47N:-K7rsm0yMV_GQ7H1DurB:-499146009) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/api.js#L22)):*
Done.

---

*[src/serviceWorker.js, line 209 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rrVwlkASjtgpdxnBL:-K7rsfLl9BRFuq6EvMeQ:-499146009) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/serviceWorker.js#L209)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jkasten2** [comment]
Review status: 4 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/sdk.js, line 922 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rrr7bfHC1qZk0Aocj:-K7rrr7cNpDVW0WzFkF8:-180485937) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/sdk.js#L922)):*
What does 1.2 mean here?

---

*[src/sdk.js, line 1166 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rsX-cLLuIOmh2xCCO:-K7rsX-daya0oKbbGKQe:-1685158066) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/28a4e98da8e68c7e3bfdd268f2894e182e1dfab2/src/sdk.js#L1166)):*
Was this just duplicated dead code? Does it live somewhere else now?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jasonpang** [comment]
*[src/sdk.js, line 922 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rrr7bfHC1qZk0Aocj:-K7rt4Q_r6NQL6SnXE6z:309445703) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/69aeed290bba6ffc498f832f468191bffbc24ffc/src/sdk.js#L922)):*
Was just trying to log where the execution was going. log(1), log(1.1), log(1.2), log(1.1.1), log(1.2.1)..etc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jasonpang** [comment]
*[src/sdk.js, line 1166 \[r1\]](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3#-K7rsX-cLLuIOmh2xCCO:-K7rtFr-4slfcdCPaV8r:1824003917) ([raw file](https://github.com/one-signal/onesignal-website-sdk/blob/28a4e98da8e68c7e3bfdd268f2894e182e1dfab2/src/sdk.js#L1166)):*
Yes, this code lives in `serviceWorker.js` now (and has for quite a few commits), so it was doing nothing here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Comment by jwilm** [comment]
Reviewed 1 of 3 files at r2, 2 of 4 files at r3.
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/one-signal/onesignal-website-sdk/3)*

**Pull request merged**
